/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dlugg' at '16/06/15 4:50 PM' with Gradle 2.4
 *
 * @author dlugg, @date 16/06/15 4:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
